import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'providers.dart';

class S {
  static const Map<String, String> _uz = {
    'app_name': 'Tabassum',
    'market': 'Market',
    'products': 'Mahsulotlar',
    'dashboard': 'Tahlil',
    'wishlist': 'Tanlangan',
    'pos': 'Kassa',
    'inventory': 'Ombor',
    'settings': 'Sozlama',
    'profile': 'Profil',
    'search': 'Qidirish...',
    'open': 'Ochish',
    'go_shopping': 'Xaridni boshlash',
    'cart_empty': 'Savat bo\'sh',
    'cart_empty_desc': 'Hali birorta mahsulot qo\'shilmadi',
    'clear_cart': 'Savatni tozalash',
    'clear_cart_confirm': 'Savatni tozalashni xohlaysizmi?',
    'cart': 'Savat',
    'added_to_cart': 'Savatga qo\'shildi',
    'total_price': 'Jami summa',
    'add_to_wishlist': 'Tanlanganlarga qo\'shish',
    'remove_from_wishlist': 'Tanlanganlardan o\'chirish',
    'buy_now': 'Sotib olish',
    'add_to_cart': 'Savatchaga qo\'shish',
    'reviews': 'Sharhlar',
    'no_reviews': 'Sharhlar hali yo\'q',
    'low_stock': 'Kam qolgan',
    'total_sales': 'Umumiy savdo',
    'total_expenses': 'Umumiy xarajatlar',
    'net_profit': 'Sof foyda',
    'recent_sales': 'Oxirgi savdolar',
    'add_inventory': 'Yangi mahsulot',
    'edit_inventory': 'Tahrirlash',
    'delete': 'O\'chirish',
    'save': 'Saqlash',
    'cancel': 'Bekor qilish',
    'sign_out': 'Chiqish',
    'email': 'Email',
    'role': 'Rol',
    'customer': 'Mijoz',
    'seller': 'Sotuvchi',
    'admin': 'Admin',
    'user_role': 'Foydalanuvchi roli',
    'unisex': 'Uniseks',
    'shop_genre': 'Do\'kon yo\'nalishi',
    'become_seller_title': 'Sotuvchi bo\'lmoqchimisiz?',
    'become_seller_desc': 'O\'z mahsulotlaringizni soting',
    'become_seller_contact': 'Sotuvchi bo\'lish uchun administrator bilan bog\'laning. Tasdiqlanganingizdan so\'ng siz do\'kon ochishingiz mumkin.',
    'admin_panel_entry': 'ADMIN PANELGA KIRISH',
    'both': 'Ikkalasi',
    'auto': 'Avto ehtiyot qismlar',
    'toys': 'O\'yinchoqlar',
    'perfumery': 'Parfumeriya',
    'clothes': 'Kiyim-kechak',
    'electronics': 'Elektronika',
    'home': 'Uy va ro\'zg\'or',
    'male': 'Erkak',
    'female': 'Ayol',
    'full_name': 'To\'liq ism',
    'phone_number': 'Telefon raqami',
    'address': 'Yetkazib berish manzili',
    'edit_profile': 'Profilni tahrirlash',
    'personal_info': 'Shaxsiy ma\'lumotlar',
    'account_settings': 'Hisob sozlamalari',
    'save_changes': 'O\'zgarishlarni saqlash',
    'updating': 'Yangilanmoqda...',
    'sort': 'Saralash',
    'filter': 'Filtrlar',
    'price_low_to_high': 'Narx: Arzonroq',
    'price_high_to_low': 'Narx: Qimmatroq',
    'newest_first': 'Yangi mahsulotlar',
    'all': 'Hammasi',
    'both_genders': 'Barchaga',
    'male_gender': 'Erkaklar',
    'female_gender': 'Ayollar',
    'apply': 'Qo\'llash',
    'reset': 'Tozalash',
    'categories': 'Kategoriyalar',
    'my_profile': 'Mening profilim',
    'my_shop': 'Mening do\'konim',
    'edit_shop': 'Do\'konni tahrirlash',
    'shop_name': 'Do\'kon nomi',
    'shop_about': 'Do\'kon haqida',
    'telegram_username': 'Telegram foydalanuvchi nomi',
    'phone': 'Telefon',
    'boutique_info': 'Butik ma\'lumotlari',
    'dark_mode': 'Tungi rejim',
    'light_mode': 'Kunduzgi rejim',
    'theme': 'Mavzu',
    'subscription': 'Obuna',
    'active': 'Faol',
    'inactive': 'Faol emas',
    'expire': 'Muddatni tugatish',
    'activate': 'Faollashtirish',
    'language': 'Til',
    'uzbek': 'O\'zbekcha',
    'russian': 'Русский',
    'no_products_found': 'Mahsulotlar topilmadi',
    'catalog': 'Mahsulotlar',
    'search_shops': 'Do\'konlarni qidirish...',
    'featured': 'Tavsiya',
    'products_count': 'mahsulot',
    'top_boutiques': 'Top Do\'konlar',
    'share_shop': 'Ulashish',
    'contact_tg': 'Telegram orqali bog\'lanish',
    'address_label': 'Manzil:',
    'about_product': 'Mahsulot haqida',
    'select_color': 'Rangni tanlang',
    'select_size': 'O\'lcham',
    'stock_count': 'dona qoldi',
    'out_of_stock': 'Sotuvda yo\'q',
    'payment': 'To\'lov',
    'my_cart': 'Mening savatcham',
    'checkout': 'Rasmiylashtirish',
    'not_logged_in': 'Tizimga kirmagansiz.',
    'wishlist_empty': 'Tanlanganlar bo\'sh',
    'error': 'Xato',
    'revenue': 'Daromad',
    'expenses': 'Xarajatlar',
    'profit': 'Foyda',
    'loss': 'Kamomad',
    'today': 'Bugun',
    'this_month': 'Bu oy',
    'revenue_7_days': 'So\'nggi 7 kun daromad',
    'top_selling': 'Eng ko\'p sotilgan',
    'low_stock_items': 'Kam qolgan mahsulotlar',
    'no_recent_sales': 'Hali savdo yo\'q',
    'add_expense': 'Xarajat qo\'shish',
    'saving': 'SAQLANMOQDA',
    'notifications': 'Bildirishnomalar',
    'create_shop': 'Do\'kon yarating',
    'record_sale': 'Savdoni qayd etish',
    'select_item': 'Mahsulotni tanlang',
    'select_variant': 'Variantni tanlang',
    'quantity': 'Soni',
    'sale_recorded': 'Savdo muvaffaqiyatli saqlandi',
    'complete_sale': 'SAVDONI YAKUNLASH',
    'profile_updated': 'Profil yangilandi',
    'shop_updated': 'Ma\'lumotlar saqlandi',
    'copy_link': 'Yuqoridagi havolani nusxalab brauzerda oching.',
    'add_color': 'BOSHQA RANG',
    'color_name': 'RANG NOMI',
    'color_hint': 'm-n. Oq',
    'size': 'O\'lcham',
    'stock': 'Qoldiq',
    'add_size': 'O\'LCHAM QO\'SHISH',
    'product_created': 'Mahsulot yaratildi!',
    'manage_variants': 'Variantlarni boshqarish',
    'inventory_not_found': 'Mahsulot topilmadi',
    'variants': 'Variantlar',
    'sales_history': 'Savdo tarixi',
    'no_variants': 'Hali variant qo\'shilmagan',
    'add_color_variants': 'Rang va variant qo\'shish',
    'color_details': 'Rang Tafsilotlari',
    'price_override': 'Maxsus narx',
    'price_override_hint': 'Ixtiyoriy, pastdagilar uchun amal qiladi',
    'sizes_stock': 'O\'LCHAMLAR VA QOLDIQ',
    'variants_title': 'VARIANTLAR (RANG VA O\'LCHAM)',
    'tshirt': 'Futbolka',
    'new_shops': 'Yangi do\'konlar',
    'see_all': 'Hammasi',
    'basic_info': 'Asosiy Ma\'lumot',
    'name_hint': 'm-n. Adidas Futbolka',
    'about_hint': 'Mahsulot haqida batafsil...',
    'pricing': 'Narxi',
    'base_price': 'Asosiy narx',
    'photos': 'RASMLAR',
    'add_photo': 'Rasm qo\'shish',
    'add_size_another': 'BOSHQA O\'LCHAM QO\'SHISH',
    'name': 'Nomi',
    'gender_hint': 'erkak / ayol / barchaga',
    'description': 'Tavsif',
    'total_revenue': 'Jami daromad',
    'items': 'dona',
    'firebase_index_required': 'Firestore index talab qilinadi',
    'firebase_index_required_to_view_sales': 'Savdo tarixini ko\'rish uchun Firestore-da index yaratishingiz kerak. Pastdagi havolani nusxalab, brauzerda oching:',
    'sales_reports': 'Savdo hisobotlari',
    'no_sales_today': 'Bugun savdo yo\'q.',
    'todays_revenue': 'Bugungi daromad',
    'sales_count': 'ta savdo',
    'unknown_shop': 'Noma\'lum do\'kon',
    'login': 'Tizimga kirish',
    'sign_up': 'Ro\'yxatdan o\'tish',
    'create_account': 'Akkaunt yaratish',
    'valid_email_required': 'Yaroqli email manzilini kiriting.',
    'password_min_length': 'Parol kamida 6 ta belgidan iborat bo\'lishi kerak.',
    'welcome_back': 'Xush\nKelibsiz',
    'create_account_title': 'Akkaunt\nYaratish',
    'enter_details': 'Davom etish uchun ma\'lumotlaringizni kiriting.',
    'password': 'Parol',
    'forgot_password': 'Parolni unutdingizmi?',
    'google_sign_in': 'Davom etish: Google',
    'auth_subtitle': 'Bozorga xush kelibsiz',
    'reset_email_sent': 'Tiklash havolasi yuborildi (spamni tekshiring)',
    'enter_email_to_reset': 'Parolni tiklash uchun pochtangizni kiriting',
    'error_loading_variants': 'Variantlarni yuklashda xato',
    'create_index': 'Indeks yaratish',
    'retry': 'Qayta urinish',
    'add_review': 'Sharh qo\'shish',
    'tap_to_rate': 'Baholash uchun bosing',
    'share_experience': 'Mahsulot haqidagi fikringizni yozing...',
    'submit_review': 'YUBORISH',
    'submitting': 'YUBORILMOQDA',
    'error_occurred': 'Xatolik yuz berdi',
    'men_clothes': 'Erkaklar',
    'women_clothes': 'Ayollar',
    'shoes': 'Oyoq kiyim',
    'accessories': 'Aksessuarlar',
    'write_review': 'Sharh yozish',
    'no_reviews_yet': 'Hali sharhlar yo\'q. Birinchi bo\'lib sharh qoldiring!',
    'update_boutique_details': 'Butik ma\'lumotlarini yangilang',
    'home_garden': 'Uy va bog\'',
    'beauty': 'Go\'zallik',
    'kids_clothes': 'Bolalar kiyimi',
    't_shirts': 'Futbolkalar',
    'hoodies': 'Xudilar',
    'jackets': 'Kurtkalar',
    'dresses': 'Ko\'ylaklar',
    'tops': 'Toplar',
    'phones': 'Telefonlar',
    'laptops': 'Noutbuklar',
    'headphones': 'Quloqchinlar',
    'auto_parts': 'Avto ehtiyot qismlar',
    'tools': 'Asbob-uskunalar',
    'sport_hobby': 'Sport va hobbi',
    'toys_kids': 'O\'yinchoqlar',
    'educational_toys': 'Rivojlantiruvchi o\'yinchoqlar',
    'perfume_men': 'Erkaklar atirlari',
    'perfume_women': 'Ayollar atirlari',
    'spare_parts': 'Ehtiyot qismlar',
    'car_accessories': 'Avto-aksessuarlar',
    'power_tools': 'Elektr asboblar',
    'hand_tools': 'Qo\'l asboblari',
    'popular_categories': 'Ommabop kategoriyalar',
    'all_categories': 'Barcha kategoriyalar',
    'search_categories': 'Kategoriyalarni qidirish...',
    'view_products': 'Mahsulotlarni ko\'rish',
    'no_subcategories': 'Ichki kategoriyalar mavjud emas',
    'all_products': 'Barcha mahsulotlar',
    'sort_by': 'Saralash',
    'sort_popular': 'Ommabopligi bo\'yicha',
    'sort_newest': 'Yangi qo\'shilganlar',
    'sort_price_asc': 'Narxi: Arzonlashish',
    'sort_price_desc': 'Narxi: Qimmatlashish',
    'sort_rating': 'Bahosi bo\'yicha',
    'brand': 'Brend',
    'brand_hint': 'Masalan: Nike, Adidas',
    'select_range': 'Sana tanlang',
    'custom_range': 'Boshqa sana...',
    'unit_price': 'Dona narxi',
    'total_amount': 'Jami summa',
    'no_products_yet': 'Hali mahsulot yo\'q',
    'shop_empty_desc': 'Bu do\'konda hozircha sotuvda mahsulotlar mavjud emas.',
    'add_first_product': 'MAHSULOT QO\'SHISH',
  };

  static const Map<String, String> _ru = {
    'app_name': 'Tabassum',
    'market': 'Маркет',
    'products': 'Товары',
    'dashboard': 'Аналитика',
    'wishlist': 'Избранное',
    'pos': 'Касса',
    'inventory': 'Склад',
    'settings': 'Настройки',
    'profile': 'Профиль',
    'search': 'Поиск...',
    'add_to_wishlist': 'Добавить в избранное',
    'remove_from_wishlist': 'Удалить из избранного',
    'buy_now': 'Купить сейчас',
    'add_to_cart': 'В корзину',
    'reviews': 'Отзывы',
    'no_reviews': 'Отзывов пока нет',
    'low_stock': 'Мало в наличии',
    'total_sales': 'Общие продажи',
    'total_expenses': 'Общие расходы',
    'net_profit': 'Чистая прибыль',
    'recent_sales': 'Последние продажи',
    'add_inventory': 'Новый товар',
    'edit_inventory': 'Редактировать',
    'delete': 'Удалить',
    'save': 'Сохранить',
    'cancel': 'Отмена',
    'sign_out': 'Выйти',
    'email': 'Email',
    'role': 'Роль',
    'customer': 'Клиент',
    'seller': 'Продавец',
    'admin': 'Админ',
    'user_role': 'Роль пользователя',
    'unisex': 'Унисекс',
    'shop_genre': 'Направление магазина',
    'become_seller_title': 'Хотите стать продавцом?',
    'become_seller_desc': 'Продавайте свои товары',
    'become_seller_contact': 'Свяжитесь с администратором, чтобы стать продавцом. После одобрения вы сможете открыть магазин.',
    'admin_panel_entry': 'ВХОД В АДМИН ПАНЕЛЬ',
    'both': 'Оба',
    'auto': 'Автозапчасти',
    'toys': 'Игрушки',
    'perfumery': 'Парфюмерия',
    'clothes': 'Одежда',
    'electronics': 'Электроника',
    'home': 'Дом и быт',
    'male': 'Мужской',
    'female': 'Женский',
    'full_name': 'Полное имя',
    'phone_number': 'Номер телефона',
    'address': 'Адрес доставки',
    'edit_profile': 'Редактировать профиль',
    'personal_info': 'Личная информация',
    'account_settings': 'Настройки аккаунта',
    'save_changes': 'Сохранить изменения',
    'updating': 'Обновление...',
    'sort': 'Сортировка',
    'filter': 'Фильтры',
    'price_low_to_high': 'Цена: дешевле',
    'price_high_to_low': 'Цена: дороже',
    'newest_first': 'Новинки',
    'all': 'Все',
    'both_genders': 'Всем',
    'male_gender': 'Мужчинам',
    'female_gender': 'Женщинам',
    'apply': 'Применить',
    'reset': 'Сбросить',
    'categories': 'Категории',
    'my_profile': 'Мой профиль',
    'my_shop': 'Мой магазин',
    'edit_shop': 'Редактировать магазин',
    'shop_name': 'Название магазина',
    'shop_about': 'О магазине',
    'telegram_username': 'Ник в Telegram',
    'phone': 'Телефон',
    'boutique_info': 'Информация о бутике',
    'dark_mode': 'Темный режим',
    'light_mode': 'Светлый режим',
    'theme': 'Тема',
    'subscription': 'Подписка',
    'active': 'Активна',
    'inactive': 'Неактивна',
    'expire': 'Истечь срок',
    'activate': 'Активировать',
    'language': 'Язык',
    'uzbek': 'O\'zbekcha',
    'russian': 'Русский',
    'no_products_found': 'Товары не найдены',
    'catalog': 'Товары',
    'search_shops': 'Поиск магазинов...',
    'featured': 'Рекомендуем',
    'products_count': 'товаров',
    'top_boutiques': 'Топ Магазины',
    'share_shop': 'Поделиться',
    'contact_tg': 'Связаться в Telegram',
    'address_label': 'Адрес:',
    'about_product': 'О товаре',
    'select_color': 'Выберите цвет',
    'select_size': 'Размер',
    'stock_count': 'шт в наличии',
    'out_of_stock': 'Нет в наличии',
    'payment': 'Оплата',
    'my_cart': 'Моя корзина',
    'checkout': 'Оформить',
    'not_logged_in': 'Не выполнен вход.',
    'wishlist_empty': 'В избранном пусто',
    'error': 'Ошибка',
    'revenue': 'Доход',
    'expenses': 'Расходы',
    'profit': 'Прибыль',
    'loss': 'Убыток',
    'today': 'Сегодня',
    'this_month': 'Этот месяц',
    'revenue_7_days': 'Доход за последние 7 дней',
    'top_selling': 'Топ продаж',
    'low_stock_items': 'Товары с низким остатком',
    'no_recent_sales': 'Продаж пока нет',
    'add_expense': 'Добавить расход',
    'saving': 'СОХРАНЕНИЕ',
    'notifications': 'Уведомления',
    'create_shop': 'Создайте магазин',
    'record_sale': 'Оформить продажу',
    'select_item': 'Выберите товар',
    'select_variant': 'Выберите вариант',
    'quantity': 'Количество',
    'sale_recorded': 'Продажа успешно сохранена',
    'complete_sale': 'ЗАВЕРШИТЬ ПРОДАЖУ',
    'profile_updated': 'Профиль обновлен',
    'shop_updated': 'Данные сохранены',
    'copy_link': 'Скопируйте ссылку и откройте в браузере.',
    'add_color': 'ДРУГОЙ ЦВЕТ',
    'color_name': 'НАЗВАНИЕ ЦВЕТА',
    'color_hint': 'напр. Белый',
    'size': 'Размер',
    'stock': 'Остаток',
    'add_size': 'ДОБАВИТЬ РАЗМЕР',
    'product_created': 'Товар создан!',
    'manage_variants': 'Управление вариантами',
    'inventory_not_found': 'Товар не найден',
    'variants': 'Варианты',
    'sales_history': 'История продаж',
    'no_variants': 'Вариантов пока нет',
    'add_color_variants': 'Добавить варианты цвета',
    'color_details': 'Детали цвета',
    'price_override': 'Особая цена',
    'price_override_hint': 'Необязательно, применится ниже',
    'sizes_stock': 'РАЗМЕРЫ И ОСТАТОК',
    'variants_title': 'ВАРИАНТЫ (ЦВЕТ И РАЗМЕР)',
    'tshirt': 'Футболка',
    'new_shops': 'Новые магазины',
    'see_all': 'Все',
    'add_size_another': 'ДОБАВИТЬ ЕЩЕ РАЗМЕР',
    'basic_info': 'ОСНОВНАЯ ИНФОРМАЦИЯ',
    'name': 'Название',
    'name_hint': 'напр. Футболка Adidas',
    'gender_hint': 'мужская / женская / унисекс',
    'description': 'Описание',
    'about_hint': 'Расскажите больше о товаре...',
    'pricing': 'Цена',
    'base_price': 'Базовая цена',
    'photos': 'ФОТО',
    'add_photo': 'Добавить фото',
    'total_revenue': 'Общий доход',
    'items': 'шт',
    'firebase_index_required': 'Требуется индекс Firestore',
    'firebase_index_required_to_view_sales': 'Для просмотра истории продаж необходим индекс в Firestore. Скопируйте ссылку и откройте в браузере:',
    'sales_reports': 'Отчеты по продажам',
    'no_sales_today': 'Сегодня продаж нет.',
    'todays_revenue': 'Доход за сегодня',
    'sales_count': 'продаж',
    'unknown_shop': 'Неизвестный магазин',
    'login': 'Войти',
    'sign_up': 'Регистрация',
    'create_account': 'Создать аккаунт',
    'valid_email_required': 'Пожалуйста, введите действительный адрес электронной почты.',
    'password_min_length': 'Пароль должен состоять как минимум из 6 символов.',
    'welcome_back': 'С возвращением',
    'create_account_title': 'Создать\nАккаунт',
    'enter_details': 'Введите ваши данные ниже, чтобы продолжить.',
    'password': 'Пароль',
    'forgot_password': 'Забыли пароль?',
    'google_sign_in': 'Продолжить через Google',
    'auth_subtitle': 'Добро пожаловать на маркетплейс',
    'reset_email_sent': 'Ссылка для восстановления отправлена (проверьте спам)',
    'enter_email_to_reset': 'Введите почту для сброса пароля',
    'error_loading_variants': 'Ошибка загрузки вариантов',
    'create_index': 'Создать индекс',
    'retry': 'Повторить',
    'add_review': 'Оставить отзыв',
    'tap_to_rate': 'Нажмите, чтобы оценить',
    'share_experience': 'Поделитесь впечатлениями о товаре...',
    'submit_review': 'ОТПРАВИТЬ',
    'submitting': 'ОТПРАВЛЯЕТСЯ',
    'error_occurred': 'Произошла ошибка',
    'men_clothes': 'Мужчинам',
    'women_clothes': 'Женщинам',
    'shoes': 'Обувь',
    'accessories': 'Аксессуары',
    'write_review': 'Написать отзыв',
    'no_reviews_yet': 'Пока нет отзывов.',
    'update_boutique_details': 'Обновите данные бутика',
    'home_garden': 'Дом и сад',
    'beauty': 'Красота',
    'kids_clothes': 'Детская одежда',
    't_shirts': 'Футболки',
    'hoodies': 'Худи',
    'jackets': 'Куртки',
    'dresses': 'Платья',
    'tops': 'Топы',
    'phones': 'Телефоны',
    'laptops': 'Ноутбуки',
    'headphones': 'Наушники',
    'auto_parts': 'Автозапчасти',
    'tools': 'Инструменты',
    'sport_hobby': 'Спорт и хобби',
    'toys_kids': 'Игрушки',
    'educational_toys': 'Развивающие игрушки',
    'perfume_men': 'Мужской парфюм',
    'perfume_women': 'Женский парфюм',
    'spare_parts': 'Запчасти',
    'car_accessories': 'Автоаксессуары',
    'power_tools': 'Электроинструменты',
    'hand_tools': 'Ручные инструменты',
    'popular_categories': 'Популярные категории',
    'all_categories': 'Все категории',
    'search_categories': 'Поиск категорий...',
    'view_products': 'Посмотреть товары',
    'no_subcategories': 'Нет подкатегорий',
    'all_products': 'Все товары',
    'sort_by': 'Сортировка',
    'sort_popular': 'По популярности',
    'sort_newest': 'Сначала новые',
    'sort_price_asc': 'Цена: по возрастанию',
    'sort_price_desc': 'Цена: по убыванию',
    'sort_rating': 'По рейтингу',
    'brand': 'Бренд',
    'brand_hint': 'Например: Nike, Adidas',
    'select_range': 'Выберите период',
    'custom_range': 'Другая дата...',
    'unit_price': 'Цена за единицу',
    'total_amount': 'Итоговая сумма',
    'no_products_yet': 'Товаров пока нет',
    'shop_empty_desc': 'В этом магазине пока нет товаров в продаже.',
    'add_first_product': 'ДОБАВИТЬ ТОВАР',
  };

  static String get(String key, String lang) {
    if (lang == 'ru') return _ru[key] ?? _uz[key] ?? key;
    return _uz[key] ?? _ru[key] ?? key;
  }
}

extension LocalizationExt on BuildContext {
  String l(String key) {
     try {
       final container = ProviderScope.containerOf(this, listen: true);
       final lang = container.read(localeProvider);
       return S.get(key, lang);
     } catch (_) {
       return S.get(key, 'uz');
     }
  }
}
